version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app # Mount the current directory to the container's /app directory
    command: ["python", "data_visualisation.py"]
